default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: rad_consumer_development

test:
  <<: *default
  database: rad_consumer_test

production:
  <<: *default
  database: rad_consumer_production
  username: rad
  password: <%= ENV['RAD_DATABASE_PASSWORD'] %>
